### ISSUE TITLE
tslib dependencies vs devDependecies in 1.x releases

### ISSUE THREAD

**Issue by lnhrdt** [piotrwitek/typesafe-actions#32]
tslib is declared under devDependencies but it makes test fail and should instead be declared under dependencies.

[I see you've fixed it](https://github.com/piotrwitek/typesafe-actions/issues/22#issuecomment-379043084) for the upcoming 2.0 (thanks!) but the issue is also present in the 1.x releases (verified in 1.1.2). Can you release a fix for the 1.x releases as well?

**Comment by piotrwitek** [comment]
@lnhrdt sure thing, I'll do it in a next hour

**Comment by piotrwitek** [comment]
resolved with https://github.com/piotrwitek/typesafe-actions/releases/tag/v1.1.3

**Comment by lnhrdt** [comment]
Thanks for the fast help @piotrwitek! I really appreciate it, and this tool looks really promising.

I'm still having problems a working application with 1.1.3 **because I can't figure out how to create a RootAction type.** It seems `getReturnOfExpression` was removed from `typesafe-actions` and `$call` the function doesn't exist (same problem as in piotrwitek/react-redux-typescript-guide#73).

I know you're cooking up some really cool stuff for v2.x but until that's ready do you have an up-to-date example using 1.1.3? The API seems to have changed so much through the 1.x versions that docs aren't helping me and I haven't been able to figure it out on my own.

**Comment by piotrwitek** [comment]
https://github.com/piotrwitek/typesafe-actions/issues/25#issuecomment-387665972

If you still want to stick to 1.1.3 the only thing I can advise is to get $call from here: https://github.com/piotrwitek/utility-types/tree/v1.1.0

**Comment by lnhrdt** [comment]
@piotrwitek awesome, thanks for the tip!
But I also just saw your update in #25 about releasing 2.x tomorrow. I'll just wait until then! 🎉
